# KingdeGuo's Blog Configuration
# 重构后的统一配置文件

# Site Information
title: "KingdeGuo's Blog"
subtitle: "技术分享 • 生活感悟 • 读书笔记"
description: "个人博客分享技术、生活和读书等内容"
author: "KingdeGuo"
email: "kingdeguo@gmail.com"
url: "https://kingdeguo.github.io"
baseurl: ""

# Social Media
social:
  github: "kingdeguo"
  twitter: ""
  linkedin: ""
  weibo: ""

# Theme Configuration
theme:
  name: "minimal-mistakes"
  remote_theme: "mmistakes/minimal-mistakes"
  skin: "default" # default, air, aqua, contrast, dark, dirt, neon, mint, plum, sunrise
  switcher:
    enabled: true
    default: "light"
    location: "header"

# Visualization System (重构后的统一配置)
visualization:
  # 核心库配置
  libraries:
    echarts:
      version: "5.4.3"
      cdn: "https://cdn.jsdelivr.net/npm/echarts@5.4.3/dist/echarts.min.js"
      local: "/assets/lib/echarts.min.js"
    chartjs:
      version: "4.4.1"
      cdn: "https://cdn.jsdelivr.net/npm/chart.js@4.4.1/dist/chart.umd.min.js"
      local: "/assets/lib/chart.min.js"
    mermaid:
      version: "10.7.0"
      cdn: "https://cdn.jsdelivr.net/npm/mermaid@10.7.0/dist/mermaid.min.js"
      local: "/assets/lib/mermaid.min.js"
    plotly:
      version: "2.27.1"
      cdn: "https://cdn.plot.ly/plotly-2.27.1.min.js"
      local: "/assets/lib/plotly.min.js"
  
  # 性能优化
  performance:
    lazy_loading: true
    preload_critical: true
    cache_strategy: "local-first"
    fallback_images: true
  
  # 渲染配置
  rendering:
    timeout: 10000
    max_retries: 3
    retry_delay: 1000
    error_handling: "graceful"

# Comments System
comments:
  provider: "giscus"
  giscus:
    repo: "KingdeGuo/kingdeguo.github.io"
    repo_id: "R_kgDOPLxeEQ"
    category: "General"
    category_id: "DIC_kwDOPLxeEc4Cs5E6"
    theme: "preferred_color_scheme"
    lang: "zh-CN"

# Analytics
analytics:
  google:
    tracking_id: "G-HXENT9GH1J"
  baidu: ""
  cnzz: ""

# Build Settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache

# Permalinks
permalink: "/:year/:month/:day/:title.html"

# Archives
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive
    tag: archive
  permalinks:
    category: '/categories/:name/'
    tag: '/tags/:name/'

# Markdown Processing
markdown: kramdown
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1

# File Processing
include:
  - _posts
  - _pages
  - _layouts
  - _includes
  - assets
  - images
  - favicon.ico
  - robots.txt
  - sitemap.xml

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
  - migrate_visualization.py
  - performance_monitor.py
  - VISUALIZATION_GUIDE.md
  - VISUALIZATION_OPTIMIZATION.md
  - performance_report.json
  - .DS_Store
