name: Check for Broken Links

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 0 * * 0' # 每周日午夜运行

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # 满足 sass-embedded gem 的版本要求
          bundler-cache: false # 禁用缓存，允许更新 lockfile

      - name: Install dependencies
        run: bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build --trace

      - name: Check for broken links
        uses: lycheeverse/lychee-action@v1
        with:
          args: --verbose --no-progress './_site/**/*.html'
          fail: true # 如果发现死链，则让工作流失败
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
